[package]
name = "test-project"
version = "2.0.3"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

description = "Test project to play around with release management"
repository = "https://github.com/badboy/test-project"
license = "MIT"

[dependencies]
